 $(document).ready(function(){
	 $("#changepwd").css("display","none");
	 $("#cpwd").click(function(){
		 $("#changepwd").css("display","block");
		 $("#box").css("display","none");
		 })
		 $("#link1").click(function(){
			 $("#link2").click();
			 })
	 })